version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nextcloud_appstore
    versions:
    - 0.7.0
    - 0.8.0
  - dependency-name: tokio
    versions:
    - 1.1.0
