version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: "02:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: "chore"
    include: "scope"
