language: rust
rust:
  - stable
  - beta
  - nightly

branches:
  only:
  - staging
  - trying
  - master

cache: cargo

before_deploy:
  - cargo build --release

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: target/release/krankerl
  skip_cleanup: true
  on:
    tags: true
