language: rust
rust:
  - stable
  - beta
  - nightly

branches:
  only:
  - staging
  - trying
  - master
  - "/^stable\\d+(\\.\\d+)?$/"
  - "/^v\\d++(\\.\\d+)?+(\\.\\d+)?+(\\.\\d+)?$/"

cache: cargo

before_install:
  - export BUILD_VERSION=$(echo "${TRAVIS_BRANCH//v/}")
  - echo "Building $BUILD_VERSION"

before_deploy:
  - cargo install -f cargo-deb
  - cargo build --release
  - cargo deb

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - target/release/krankerl
    - target/debian/krankerl_$BUILD_VERSION_amd64.deb 
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_RUST_VERSION == stable

