[package]
name = "krankerl"
version = "0.7.0"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]
description = "A CLI helper to manage Nextcloud apps"
license-file = "LICENSE"
keywords = ["nextcloud", "cli"]
categories = ["development-tools", "development-tools::build-utils"]

[badges]
travis-ci = { repository = "ChristophWurst/krankerl", branch = "master" }

[dependencies]
base64 = "0.9"
composer = "0.1"
docopt = "0.8"
failure = "0.1.1"
flate2 = "1.0"
futures = "0.2"
futures-cpupool = "0.1"
hex = "0.3"
globset = "0.3.0"
nextcloud_appinfo = "0.3.0"
nextcloud_appsignature = "0.2.0"
nextcloud_appstore = "0.3.1"
npm_scripts = "0.1.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tar = "0.4.15"
tokio-core = "0.1"
toml = "0.4.6"
openssl = "0.10"
pathdiff = "0.1.0"
walkdir = "2.1.4"
xdg = "2.1.0"

[dev-dependencies]
fs_extra = "1.1.0"
tempdir = "0.3"
