[package]
name = "krankerl"
version = "0.2.0"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]

[dependencies]
base64 = "0.7"
docopt = "0.8"
futures = "0.1"
futures-cpupool = "0.1"
hex = "0.2"
nextcloud_appinfo = "0.2.0"
nextcloud_appsignature = "0.1.0"
nextcloud_appstore = "0.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
openssl = "0.9"
walkdir = "1"
xdg = "2.1.0"
