[package]
name = "krankerl"
version = "0.2.0"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]

[dependencies]
base64 = "0.7"
docopt = "0.8"
flate2 = "0.2"
futures = "0.1"
futures-cpupool = "0.1"
hex = "0.2"
globset = "0.2.1"
nextcloud_appinfo = "0.2.0"
nextcloud_appsignature = "0.1.0"
nextcloud_appstore = "0.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tar = "0.4.13"
tokio-core = "0.1"
toml = "0.4.5"
openssl = "0.9"
pathdiff = "0.1.0"
walkdir = "2.0.1"
xdg = "2.1.0"
