[package]
name = "krankerl"
version = "0.12.3"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]
description = "A CLI helper to manage Nextcloud apps"
license-file = "LICENSE"
keywords = ["nextcloud", "cli"]
categories = ["development-tools", "development-tools::build-utils"]
edition = "2018"

[badges]
travis-ci = { repository = "ChristophWurst/krankerl", branch = "master" }

[dependencies]
base64 = "0.13"
composer = "0.2"
docopt = "1.1"
dirs = "3.0"
failure = "0.1.8"
flate2 = "1.0"
hex = "0.4"
ignore = "0.4.17"
git2 = "0.13"
nextcloud_appinfo = "0.6.0"
nextcloud_appsignature = "0.5.0"
nextcloud_appstore = "0.6.0"
npm_scripts = "0.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tar = "0.4.30"
tempdir = "0.3"
tokio = { version = "0.3", features = ["full"] }
toml = "0.5.7"
pathdiff = "0.2.0"
xdg = "2.2.0"

[dev-dependencies]
fs_extra = "1.2.0"
