[package]
name = "krankerl"
version = "0.10.1"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]
description = "A CLI helper to manage Nextcloud apps"
license-file = "LICENSE"
keywords = ["nextcloud", "cli"]
categories = ["development-tools", "development-tools::build-utils"]

[badges]
travis-ci = { repository = "ChristophWurst/krankerl", branch = "master" }

[dependencies]
base64 = "0.10"
composer = "0.1"
docopt = "1.1"
failure = "0.1.5"
flate2 = "1.0"
futures = "0.1"
hex = "0.3"
indicatif = "0.11.0"
ignore = "0.4.9"
git2 = "0.9"
globset = "0.4.4"
nextcloud_appinfo = "0.4.1"
nextcloud_appsignature = "0.3.0"
nextcloud_appstore = "0.4.0"
npm_scripts = "0.1.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tar = "0.4.26"
tempdir = "0.3"
tokio = "0.1.22"
toml = "0.5.1"
pathdiff = "0.1.0"
xdg = "2.2.0"

[dev-dependencies]
fs_extra = "1.1.0"
