[package]
name = "krankerl"
version = "0.10.1"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]
description = "A CLI helper to manage Nextcloud apps"
license-file = "LICENSE"
keywords = ["nextcloud", "cli"]
categories = ["development-tools", "development-tools::build-utils"]
edition = "2018"

[badges]
travis-ci = { repository = "ChristophWurst/krankerl", branch = "master" }

[dependencies]
base64 = "0.11"
composer = "0.2"
docopt = "1.1"
dirs = "2.0"
failure = "0.1.6"
flate2 = "1.0"
futures = "0.1"
hex = "0.4"
indicatif = "0.13.0"
ignore = "0.4.10"
git2 = "0.11"
globset = "0.4.4"
nextcloud_appinfo = "0.5.0"
nextcloud_appsignature = "0.4.0"
nextcloud_appstore = "0.4.0"
npm_scripts = "0.2.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tar = "0.4.26"
tempdir = "0.3"
tokio = "0.2.6"
toml = "0.5.5"
pathdiff = "0.1.0"
xdg = "2.2.0"

[dev-dependencies]
fs_extra = "1.1.0"
