[package]
name = "krankerl"
version = "0.9.4"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]
description = "A CLI helper to manage Nextcloud apps"
license-file = "LICENSE"
keywords = ["nextcloud", "cli"]
categories = ["development-tools", "development-tools::build-utils"]

[badges]
travis-ci = { repository = "ChristophWurst/krankerl", branch = "master" }

[dependencies]
base64 = "0.9"
composer = "0.1"
docopt = "1.0"
failure = "0.1.2"
flate2 = "1.0"
futures = "0.1"
hex = "0.3"
indicatif = "0.9.0"
globset = "0.4.2"
nextcloud_appinfo = "0.3.0"
nextcloud_appsignature = "0.3.0"
nextcloud_appstore = "0.4.0"
npm_scripts = "0.1.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tar = "0.4.17"
tokio = "0.1.10"
toml = "0.4.7"
pathdiff = "0.1.0"
walkdir = "2.2.5"
xdg = "2.1.0"

[dev-dependencies]
fs_extra = "1.1.0"
tempdir = "0.3"
