name: Test

on: pull_request

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
    - uses: Swatinem/rust-cache@v1
    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
